
FROM openjdk:11-jdk-alpine
VOLUME /tmp
ARG JAVA_OPTS
ENV JAVA_OPTS=$JAVA_OPTS
ADD target/ayudacompra-api-0.0.1-SNAPSHOT.jar ayudacompra-api.jar
EXPOSE 9000
ENTRYPOINT exec java $JAVA_OPTS -jar ayudacompra-api.jar
# For Spring-Boot project, use the entrypoint below to reduce Tomcat startup time.
#ENTRYPOINT exec java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar ayudacompra-api.jar
